/**
 * @author {{{author}}}
 * @since {{{date}}}
 */

(function () {
    'use strict';

    angular.module(moduleName)
        .controller('{{{serviceName}}}', {{{serviceName}}});

    /* @ngInject */
    function {{{serviceName}}} ($log) {
        var service = {};

        /// Service Public API ///
        service.method = method;
        ///////////////

        return service;

        ///////////////

        function method() {
            // TODO autogenerated method stub...
        }

    }
})();
